package com.pm.inventoryservice.model;

public enum MovementType {
    RESERVATION,
    RESERVATION_CONFIRMED,
    RELEASE,
    DEDUCTION,
    RESTOCK,
    ADJUSTMENT,
    RESERVATION_RELEASED,
    RETURN,
    CREATE_INVENTORY,
    INVENTORY_UPDATED,
    STOCK_ADDED,
    INVENTORY_CREATED,
    STOCK_REMOVED
}
